version: '3'

services:
  lisum_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
    - redis
    # environment:
    # - REDIS_DSN=redis://redis:6379/db
    network_mode: "host"

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    environment:
    - ALLOW_EMPTY_PASSWORD=yes

networks:
  host:
    driver: host
